version: '2'
services:
  postgres:
    image: postgres:9.6
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgres-data:/var/lib/postgresql/data
  sonarqube:  # I got issue with sonarqube working with in docker wsl2 had to do : wsl -d docker-desktop && sysctl -w vm.max_map_count=262144
    image: sonarqube:lts
    ports:
      - 9000:9000
      - 9092:9092
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres

networks:
  jenkins:
volumes:
  postgres-data: